create table if not exists ifwt_kyc_coincidencias
(
    id_coincidencia          int auto_increment primary key,
    id_kyc                   int            not null comment 'Identificador del cliente encontrado en listas negras',
    curp                     varchar(20)    null comment 'CURP con el que se validó la existencia en listas negras',
    rfc                      varchar(20)    null comment 'RFC con el que se validó la existencia en listas negras',
    id                       varchar(50)    null comment 'Identificador único registrado en la lista negra',
    nombres                  varchar(255)   null comment 'Nombre(s) persona física',
    apellidos                varchar(255)   null comment 'Apellidos de persona física o Razón Social',
    nombre_completo          varchar(255)   null comment 'Nombre completo empezando por nombre(s) y apellidos para personas. Para entidades razón social.',
    nombre_alternativo       varchar(255)   null comment 'Nombre completo empezando por apellidos seguido de su(s) nombre(s) para personas. Para entidades razón social.',
    ortografia_alternativa   varchar(255)   null comment 'Ortografía alternativa para el nombre principal. Puede contener apellidos, nombres o ambos. No contiene nombres adicionales a los de los campos de nombre principal',
    curp_encontrada          varchar(20)    null comment 'Contendrá CURP si es persona física y si dentro de la información de listas negras se encuentra la información',
    rfc_encontrado           varchar(20)    null comment 'Contendrá RFC si es persona física o moral y si dentro de la información de listas negras se encuentra la información',
    alias                    varchar(255)   null comment 'Las entidades aparecerán en letras mayúsculas. Para personas, puede contener apellidos, nombres o ambos. Contiene nombres que difieren parcial o completamente del nombre contenido en los campos de nombre primario o contienen nombres además del nombre contenido en los campos de nombre primario.',
    genero                   varchar(5)     null comment 'Género de la persona. No aplica para una entidad.',
    edad                     varchar(10)    null comment 'Edad. Proporciona una aproximación de edad cuando se desconoce la fecha exacta de nacimiento.',
    fec_edad_valida          varchar(15)    null comment 'Proporciona la fecha en que el valor de EDAD era válido.',
    fec_nacimiento           varchar(15)    null comment 'Fecha de nacimiento. Aplica persona física',
    lugar_nacimiento         varchar(255)   null comment 'Lugar de nacimiento para personas. En blanco para entidades.',
    fec_fallecimiento        varchar(15)    null comment 'En su caso, la fecha de fallecimiento de la persona. En blanco para entidades.',
    nss                      varchar(50)    null comment 'Número de seguridad social',
    puntuacion               decimal(10, 4) null comment 'Puntuación',
    categoria                varchar(50)    null comment 'Descripción de una o dos palabras de la justificación principal para la entrada que figura',
    sub_categoria            varchar(50)    null comment 'Especifica si la entrada está expuesta políticamente (PEP) o no. Esto incluye PEP, SOE, parientes inmediatos y asociados cercanos.',
    titulo                   varchar(50)    null comment 'Título real, militar o académico, como: General, Baronesa, Comandante, Doctor, Juez, Profesor',
    posicion                 varchar(255)   null comment 'Puesto social o político (no ocupación) como embajador, concejal, ministro del gabinete, consejero, director, ejecutivo superior. Solo aplicable a los perfiles PEP.',
    pasaportes               varchar(255)   null comment 'Números de pasaporte',
    ubicaciones              text           null comment 'País, Región (Estado / Provincia), Ciudad y dirección donde hay información disponible.',
    paises                   varchar(255)   null comment 'Para particulares, país de nacionalidad o ciudadanía. Para las entidades, el país donde está registrada la entidad.',
    empresas                 varchar(255)   null comment 'Compañía relacionado a la persona reportada',
    vinculado_a              varchar(255)   null comment 'Personas con los que se entiende que el perfil está relacionado',
    keywords                 varchar(255)   null comment 'Lista de todas las sanciones, listas regulatorias y policiales en las que se ha incluido el perfil',
    info_adicional           text           null comment 'Información biográfica y de identificación adicional sobre entradas perfiladas, relaciones, informes negativos o de riesgo, así como el texto completo de todas las entradas de sanciones (cuando corresponda), así como información de respaldo y relevante.',
    recursos_externos        text           null comment 'Lista de todas las fuentes públicas, incluidas las fuentes gubernamentales y de medios',
    cve_lista                varchar(50)    null comment 'Indica en que tipo de lista se encontró el hit. Puede ser (QsQ, World Check, etc.)',
    ds_lista                 varchar(50)    null comment 'Nombre de la lista donde se encontró el hit',
    dependencia              varchar(255)   null comment 'Dependencia a la cual esta asociado un PEP nacional.',
    parentesco               varchar(255)   null comment 'Parentesco con algún relacionado en listas negras.',
    ingresos                 varchar(255)   null comment 'Ingresos reportados por el match en la lista',
    area                     varchar(255)   null comment 'Área geográfica del hit reportado.',
    fec_creacion_perfil      varchar(15)    null comment 'Fecha en que el perfil se creó inicialmente.',
    fec_actualizacion_perfil varchar(15)    null comment 'Categorización de la actualización más reciente.',
    ds_atributo_01           varchar(255)   null comment 'Atributo uno adicional',
    ds_atributo_02           varchar(255)   null comment 'Atributo dos adicional',
    ds_atributo_03           varchar(255)   null comment 'Atributo tres adicional',
    ds_atributo_04           varchar(255)   null comment 'Atributo cuatro adicional',
    sw_pep                   boolean        null comment 'Indicador para Personas Políticamente Expuestas',
    creado_por               varchar(70)    not null comment 'Usuario que crea el registro',
    fec_creacion             datetime       not null comment 'Fecha de creación del registro',
    actualizado_por          varchar(70)    null comment 'Usuario que actualiza el registro',
    fec_actualizacion        datetime       null comment 'Fecha de actualización del registro'
)
    COMMENT 'Tabla que almacenará las coincidencias de personas en listas negras';
